# Generated by Django 4.1.4 on 2023-05-28 20:14

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_teammember_team'),
        ('users', '0003_user_associated_team_user_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='associated_team',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_name',
        ),
        migrations.AddField(
            model_name='user',
            name='associated_team_members',
            field=models.ManyToManyField(to='tracker.teammember'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
