# Generated by Django 4.1.4 on 2023-01-22 04:20

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, null=True)),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
                ('busts', models.IntegerField(default=0)),
                ('repetition_number', models.IntegerField(editable=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], max_length=2, primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('R', 'Rookie'), ('I', 'Inter'), ('O', 'Open')], max_length=100, null=True)),
                ('foundation', models.DateField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('jump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.jump')),
                ('point_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_point_1', to='tracker.point')),
                ('point_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_point_2', to='tracker.point')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(choices=[('P', 'Point'), ('T', 'Tail'), ('I', 'Inside-Center'), ('O', 'Outside-Center')], max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.team')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('pool_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('point_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_point_1', to='tracker.point')),
                ('point_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_point_2', to='tracker.point')),
                ('point_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_point_3', to='tracker.point')),
                ('point_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_point_4', to='tracker.point')),
                ('point_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_point_5', to='tracker.point')),
            ],
        ),
        migrations.CreateModel(
            name='JumpAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number', models.IntegerField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.BooleanField()),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('jump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.jump')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.point')),
            ],
        ),
        migrations.AddField(
            model_name='jump',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.pool'),
        ),
        migrations.AddField(
            model_name='jump',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.team'),
        ),
        migrations.AddField(
            model_name='jump',
            name='team_members',
            field=models.ManyToManyField(to='tracker.teammember'),
        ),
        migrations.AlterUniqueTogether(
            name='jump',
            unique_together={('team', 'pool', 'date', 'repetition_number')},
        ),
    ]
